import type Database from "better-sqlite3";
import type { Logger } from "./logger.js";
import type { GeminiCliRunner, GeminiRuntimeSurface } from "../shared/provider-runtime/gemini-runtime.js";
import type { AntigravityCliLocatorPort } from "../integrations/antigravity-cli/antigravity-cli.types.js";
import type { AntigravityInteractiveProcessLauncher } from "../integrations/antigravity-cli/antigravity-auth.types.js";
import type { ClaudeCliRunner, ClaudeRuntimeSurface } from "../shared/provider-runtime/claude-runtime.js";
import type { ClaudeCliLocatorPort, ClaudeCliStatusSnapshot } from "../integrations/claude-cli/claude-cli.types.js";
import type { ClaudeInteractiveProcessLauncher } from "../integrations/claude-cli/claude-auth.types.js";
import type { CursorCliCommandRunnerPort, CursorCliLocatorPort, CursorCliStatusSnapshot } from "../integrations/cursor-cli/cursor-cli.types.js";
import type { CursorInteractiveProcessLauncher } from "../integrations/cursor-cli/cursor-auth.types.js";
import type { ProviderGatewayDatabaseContext } from "./database.js";

export type ProviderGatewayModuleOptions = {
  appEnv?: "development" | "test" | "production";
  logLevel?: "debug" | "info" | "warn" | "error";
  databaseUrl?: string;
  sqlite?: Database.Database;
  database?: ProviderGatewayDatabaseContext;
  appApiKeyPepper: string;
  credentialEncryptionKey?: string;
  allowInsecureCredentialStorage?: boolean;
  publicBaseUrl?: string;
  codexClientId?: string;
  providerAuthCallbackMode?: "host" | "local-cli";
  providerAuthPublicBaseUrl?: string;
  providerAuthPrefix?: string;
  providerAuthRefreshSkewMs?: number;
  providerAuthLifecycleAuditDir?: string;
  codexOAuthAuditDir?: string;
  codexRequestAuditDir?: string;
  codexAccountDiscoveryDir?: string;
  geminiRequestAuditDir?: string;
  cursorRequestAuditDir?: string;
  geminiRuntimeSurface?: GeminiRuntimeSurface;
  antigravityCliBin?: string;
  antigravityCliTimeoutMs?: number;
  antigravityCliMaxConcurrentProcesses?: number;
  antigravityCliMaxQueuedProcesses?: number;
  antigravityCliRunner?: GeminiCliRunner;
  antigravityCliLocator?: AntigravityCliLocatorPort;
  antigravityAuthProcessLauncher?: AntigravityInteractiveProcessLauncher;
  localCliMaxConcurrentProcesses?: number;
  localCliMaxQueuedProcesses?: number;
  antigravityAuthFlowTimeoutMs?: number;
  antigravityAuthFlowTtlMs?: number;
  claudeRequestAuditDir?: string;
  claudeRuntimeSurface?: ClaudeRuntimeSurface;
  claudeCliBin?: string;
  claudeCliTimeoutMs?: number;
  claudeCliMaxConcurrentProcesses?: number;
  claudeCliMaxQueuedProcesses?: number;
  claudeCliRunner?: ClaudeCliRunner;
  claudeCliLocator?: ClaudeCliLocatorPort;
  claudeCliStatusService?: { inspect(): Promise<ClaudeCliStatusSnapshot> };
  claudeAuthProcessLauncher?: ClaudeInteractiveProcessLauncher;
  claudeAuthFlowTimeoutMs?: number;
  claudeAuthFlowTtlMs?: number;
  cursorCliPath?: string;
  cursorCliTimeoutMs?: number;
  cursorCliMaxConcurrentProcesses?: number;
  cursorCliMaxQueuedProcesses?: number;
  cursorCliLocator?: CursorCliLocatorPort;
  cursorCliRunner?: CursorCliCommandRunnerPort;
  cursorCliStatusService?: { inspect(): Promise<CursorCliStatusSnapshot> };
  cursorAuthProcessLauncher?: CursorInteractiveProcessLauncher;
  cursorAuthFlowTimeoutMs?: number;
  cursorAuthFlowTtlMs?: number;
  logger?: Logger;
  runMigrations?: boolean;
};
